### ISSUE TITLE
居然不更新了= =

### ISSUE THREAD

**Issue by CatchPig51** [Hehesheng/k210#5]
想知道多核自动调度的实现思路是咋样的？

**Comment by Hehesheng** [comment]
很久没用过k210了，我看你也在k210上运行rtt，可以看看https://github.com/wuyi233/a-electronic-robot-with-k210-esp32-rt-thread/blob/master/src/idle.c 这个文件里的实现

**Comment by CatchPig51** [comment]
好滴，太可惜了= =
